-- Auto-generated from src/domain/badgeCatalog.ts (106 badges).
insert into badges (craft, name, slug, description, icon_key) values
  ('rapper', 'Golden Voice', 'rapper.golden-voice', 'Golden Voice — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-voice'),
  ('rapper', 'Lyrical Pen', 'rapper.lyrical-pen', 'Lyrical Pen — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'lyrical-pen'),
  ('rapper', 'Steady Flow', 'rapper.steady-flow', 'Steady Flow — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'steady-flow'),
  ('rapper', 'Punchline', 'rapper.punchline', 'Punchline — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'punchline'),
  ('rapper', 'Freestyle', 'rapper.freestyle', 'Freestyle — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'freestyle'),
  ('rapper', 'Storyteller', 'rapper.storyteller', 'Storyteller — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'storyteller'),
  ('rapper', 'Breath Control', 'rapper.breath-control', 'Breath Control — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'breath-control'),
  ('rapper', 'Crowd Mover', 'rapper.crowd-mover', 'Crowd Mover — a rapper badge. Climb Bronze → Diamond with Love + verified Proof.', 'crowd-mover'),
  ('singer', 'Golden Voice', 'singer.golden-voice', 'Golden Voice — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-voice'),
  ('singer', 'Range', 'singer.range', 'Range — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'range'),
  ('singer', 'Runs & Riffs', 'singer.runs-and-riffs', 'Runs & Riffs — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'runs-and-riffs'),
  ('singer', 'Falsetto', 'singer.falsetto', 'Falsetto — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'falsetto'),
  ('singer', 'Harmony', 'singer.harmony', 'Harmony — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'harmony'),
  ('singer', 'Songbird', 'singer.songbird', 'Songbird — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'songbird'),
  ('singer', 'Ad-Lib', 'singer.ad-lib', 'Ad-Lib — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'ad-lib'),
  ('singer', 'Pitch Perfect', 'singer.pitch-perfect', 'Pitch Perfect — a singer badge. Climb Bronze → Diamond with Love + verified Proof.', 'pitch-perfect'),
  ('producer', 'Crate Digger', 'producer.crate-digger', 'Crate Digger — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'crate-digger'),
  ('producer', '808 Architect', 'producer.808-architect', '808 Architect — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', '808-architect'),
  ('producer', 'Sample Surgeon', 'producer.sample-surgeon', 'Sample Surgeon — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'sample-surgeon'),
  ('producer', 'Melody Maker', 'producer.melody-maker', 'Melody Maker — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'melody-maker'),
  ('producer', 'Drum Programmer', 'producer.drum-programmer', 'Drum Programmer — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'drum-programmer'),
  ('producer', 'Mixdown', 'producer.mixdown', 'Mixdown — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'mixdown'),
  ('producer', 'Hitmaker', 'producer.hitmaker', 'Hitmaker — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'hitmaker'),
  ('producer', 'Loop Lord', 'producer.loop-lord', 'Loop Lord — a producer badge. Climb Bronze → Diamond with Love + verified Proof.', 'loop-lord'),
  ('photographer', 'Golden Eye', 'photographer.golden-eye', 'Golden Eye — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-eye'),
  ('photographer', 'Golden Hour', 'photographer.golden-hour', 'Golden Hour — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-hour'),
  ('photographer', 'Studio Light', 'photographer.studio-light', 'Studio Light — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'studio-light'),
  ('photographer', 'Portrait', 'photographer.portrait', 'Portrait — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'portrait'),
  ('photographer', 'Street', 'photographer.street', 'Street — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'street'),
  ('photographer', 'Editorial', 'photographer.editorial', 'Editorial — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'editorial'),
  ('photographer', 'Retoucher', 'photographer.retoucher', 'Retoucher — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'retoucher'),
  ('photographer', 'Fast Shutter', 'photographer.fast-shutter', 'Fast Shutter — a photographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'fast-shutter'),
  ('videographer', 'Cinematic Eye', 'videographer.cinematic-eye', 'Cinematic Eye — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'cinematic-eye'),
  ('videographer', 'Color Grade', 'videographer.color-grade', 'Color Grade — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'color-grade'),
  ('videographer', 'One-Take', 'videographer.one-take', 'One-Take — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'one-take'),
  ('videographer', 'Drone', 'videographer.drone', 'Drone — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'drone'),
  ('videographer', 'Music Video', 'videographer.music-video', 'Music Video — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'music-video'),
  ('videographer', 'Editor', 'videographer.editor', 'Editor — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'editor'),
  ('videographer', 'B-Roll', 'videographer.b-roll', 'B-Roll — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'b-roll'),
  ('videographer', 'Documentary', 'videographer.documentary', 'Documentary — a videographer badge. Climb Bronze → Diamond with Love + verified Proof.', 'documentary'),
  ('model', 'Golden Smile', 'model.golden-smile', 'Golden Smile — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-smile'),
  ('model', 'Pose Striker', 'model.pose-striker', 'Pose Striker — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'pose-striker'),
  ('model', 'Runway Walk', 'model.runway-walk', 'Runway Walk — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'runway-walk'),
  ('model', 'Editorial Look', 'model.editorial-look', 'Editorial Look — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'editorial-look'),
  ('model', 'Expression', 'model.expression', 'Expression — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'expression'),
  ('model', 'Commercial', 'model.commercial', 'Commercial — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'commercial'),
  ('model', 'Fitness', 'model.fitness', 'Fitness — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'fitness'),
  ('model', 'Print', 'model.print', 'Print — a model badge. Climb Bronze → Diamond with Love + verified Proof.', 'print'),
  ('barber', 'Golden Steady Hand', 'barber.golden-steady-hand', 'Golden Steady Hand — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'golden-steady-hand'),
  ('barber', 'Fade Master', 'barber.fade-master', 'Fade Master — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'fade-master'),
  ('barber', 'Line-Up', 'barber.line-up', 'Line-Up — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'line-up'),
  ('barber', 'Design Cut', 'barber.design-cut', 'Design Cut — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'design-cut'),
  ('barber', 'Speed', 'barber.speed', 'Speed — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'speed'),
  ('barber', 'Beard Sculptor', 'barber.beard-sculptor', 'Beard Sculptor — a barber badge. Climb Bronze → Diamond with Love + verified Proof.', 'beard-sculptor'),
  ('dj', 'Beatmatch', 'dj.beatmatch', 'Beatmatch — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'beatmatch'),
  ('dj', 'Crowd Read', 'dj.crowd-read', 'Crowd Read — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'crowd-read'),
  ('dj', 'Scratch', 'dj.scratch', 'Scratch — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'scratch'),
  ('dj', 'Transition', 'dj.transition', 'Transition — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'transition'),
  ('dj', 'Set Builder', 'dj.set-builder', 'Set Builder — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'set-builder'),
  ('dj', 'Open Format', 'dj.open-format', 'Open Format — a dj badge. Climb Bronze → Diamond with Love + verified Proof.', 'open-format'),
  ('dancer', 'Footwork', 'dancer.footwork', 'Footwork — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'footwork'),
  ('dancer', 'Freestyle', 'dancer.freestyle', 'Freestyle — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'freestyle'),
  ('dancer', 'Choreographer', 'dancer.choreographer', 'Choreographer — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'choreographer'),
  ('dancer', 'In Sync', 'dancer.in-sync', 'In Sync — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'in-sync'),
  ('dancer', 'Flexibility', 'dancer.flexibility', 'Flexibility — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'flexibility'),
  ('dancer', 'Battle Tested', 'dancer.battle-tested', 'Battle Tested — a dancer badge. Climb Bronze → Diamond with Love + verified Proof.', 'battle-tested'),
  ('actor', 'Range', 'actor.range', 'Range — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'range'),
  ('actor', 'Improv', 'actor.improv', 'Improv — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'improv'),
  ('actor', 'Monologue', 'actor.monologue', 'Monologue — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'monologue'),
  ('actor', 'Voice & Accent', 'actor.voice-and-accent', 'Voice & Accent — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'voice-and-accent'),
  ('actor', 'On-Camera', 'actor.on-camera', 'On-Camera — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'on-camera'),
  ('actor', 'Stage Combat', 'actor.stage-combat', 'Stage Combat — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'stage-combat'),
  ('actor', 'Martial Arts', 'actor.martial-arts', 'Martial Arts — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'martial-arts'),
  ('actor', 'Stunts', 'actor.stunts', 'Stunts — a actor badge. Climb Bronze → Diamond with Love + verified Proof.', 'stunts'),
  ('graphic_designer', 'Logo Smith', 'graphic_designer.logo-smith', 'Logo Smith — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'logo-smith'),
  ('graphic_designer', 'Type Master', 'graphic_designer.type-master', 'Type Master — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'type-master'),
  ('graphic_designer', 'Brand Builder', 'graphic_designer.brand-builder', 'Brand Builder — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'brand-builder'),
  ('graphic_designer', 'Good Drawer', 'graphic_designer.good-drawer', 'Good Drawer — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'good-drawer'),
  ('graphic_designer', 'Illustrator', 'graphic_designer.illustrator', 'Illustrator — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'illustrator'),
  ('graphic_designer', 'Layout', 'graphic_designer.layout', 'Layout — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'layout'),
  ('graphic_designer', 'Album Cover', 'graphic_designer.album-cover', 'Album Cover — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'album-cover'),
  ('graphic_designer', 'Motion', 'graphic_designer.motion', 'Motion — a graphic designer badge. Climb Bronze → Diamond with Love + verified Proof.', 'motion'),
  ('makeup_artist', 'Flawless Beat', 'makeup_artist.flawless-beat', 'Flawless Beat — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'flawless-beat'),
  ('makeup_artist', 'Glam', 'makeup_artist.glam', 'Glam — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'glam'),
  ('makeup_artist', 'SFX', 'makeup_artist.sfx', 'SFX — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'sfx'),
  ('makeup_artist', 'Bridal', 'makeup_artist.bridal', 'Bridal — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'bridal'),
  ('makeup_artist', 'Editorial', 'makeup_artist.editorial', 'Editorial — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'editorial'),
  ('makeup_artist', 'Brow Architect', 'makeup_artist.brow-architect', 'Brow Architect — a makeup artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'brow-architect'),
  ('tattoo_artist', 'Fine Line', 'tattoo_artist.fine-line', 'Fine Line — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'fine-line'),
  ('tattoo_artist', 'Color Packing', 'tattoo_artist.color-packing', 'Color Packing — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'color-packing'),
  ('tattoo_artist', 'Black & Grey', 'tattoo_artist.black-and-grey', 'Black & Grey — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'black-and-grey'),
  ('tattoo_artist', 'Realism', 'tattoo_artist.realism', 'Realism — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'realism'),
  ('tattoo_artist', 'Script', 'tattoo_artist.script', 'Script — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'script'),
  ('tattoo_artist', 'Cover-Up', 'tattoo_artist.cover-up', 'Cover-Up — a tattoo artist badge. Climb Bronze → Diamond with Love + verified Proof.', 'cover-up'),
  ('writer', 'The Pen', 'writer.the-pen', 'The Pen — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'the-pen'),
  ('writer', 'Hook Smith', 'writer.hook-smith', 'Hook Smith — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'hook-smith'),
  ('writer', 'Author', 'writer.author', 'Author — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'author'),
  ('writer', 'Poet', 'writer.poet', 'Poet — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'poet'),
  ('writer', 'Screenwriter', 'writer.screenwriter', 'Screenwriter — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'screenwriter'),
  ('writer', 'Ghostwriter', 'writer.ghostwriter', 'Ghostwriter — a writer badge. Climb Bronze → Diamond with Love + verified Proof.', 'ghostwriter'),
  ('fashion', 'Tailor', 'fashion.tailor', 'Tailor — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'tailor'),
  ('fashion', 'Streetwear', 'fashion.streetwear', 'Streetwear — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'streetwear'),
  ('fashion', 'Pattern Maker', 'fashion.pattern-maker', 'Pattern Maker — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'pattern-maker'),
  ('fashion', 'Drip', 'fashion.drip', 'Drip — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'drip'),
  ('fashion', 'Custom', 'fashion.custom', 'Custom — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'custom'),
  ('fashion', 'Sustainable', 'fashion.sustainable', 'Sustainable — a fashion badge. Climb Bronze → Diamond with Love + verified Proof.', 'sustainable')
on conflict (slug) do nothing;
